import { pool } from './postgres.js';

export async function initPostgresSchema() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS products (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      brand TEXT NOT NULL DEFAULT '',
      category TEXT NOT NULL DEFAULT '',
      presentation TEXT NOT NULL DEFAULT '',
      flavors TEXT NOT NULL DEFAULT '[]',
      price_retail DOUBLE PRECISION NOT NULL DEFAULT 0,
      price_wholesale DOUBLE PRECISION NOT NULL DEFAULT 0,
      stock INTEGER NOT NULL DEFAULT 0,
      servings INTEGER NOT NULL DEFAULT 0,
      serving_size TEXT NOT NULL DEFAULT '',
      image TEXT NOT NULL DEFAULT '',
      badges TEXT NOT NULL DEFAULT '[]',
      tag TEXT NOT NULL DEFAULT '',
      popularity INTEGER NOT NULL DEFAULT 0,
      macros TEXT NOT NULL DEFAULT '{}',
      benefits TEXT NOT NULL DEFAULT '[]',
      usage TEXT NOT NULL DEFAULT '',
      warnings TEXT NOT NULL DEFAULT '[]',
      description TEXT NOT NULL DEFAULT '',
      active INTEGER NOT NULL DEFAULT 1,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS combos (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      note TEXT NOT NULL DEFAULT '',
      items TEXT NOT NULL DEFAULT '[]',
      discount DOUBLE PRECISION NOT NULL DEFAULT 0,
      active INTEGER NOT NULL DEFAULT 1
    );

    CREATE TABLE IF NOT EXISTS reviews (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product TEXT NOT NULL,
      name TEXT NOT NULL,
      stars INTEGER NOT NULL,
      text TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      status TEXT NOT NULL DEFAULT 'approved'
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      price_mode TEXT NOT NULL,
      customer_name TEXT NOT NULL DEFAULT '',
      notes TEXT NOT NULL DEFAULT '',
      lines TEXT NOT NULL,
      total DOUBLE PRECISION NOT NULL,
      status TEXT NOT NULL DEFAULT 'nuevo'
    );

    CREATE TABLE IF NOT EXISTS gallery (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      file TEXT NOT NULL UNIQUE,
      alt TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS gallery_removed (
      file TEXT PRIMARY KEY,
      removed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS admins (
      username TEXT PRIMARY KEY,
      salt TEXT NOT NULL,
      hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'admin',
      active INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_products_active
      ON products(active);

    CREATE INDEX IF NOT EXISTS idx_products_popularity
      ON products(popularity DESC);

    CREATE INDEX IF NOT EXISTS idx_reviews_status
      ON reviews(status);

    CREATE INDEX IF NOT EXISTS idx_orders_status
      ON orders(status);
  `);
}